version: 2
updates:
  - package-ecosystem: "npm"  # Si usas yarn.lock, c√°mbialo a "yarn"
    directory: "/client"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"  # o "yarn"
    directory: "/server"
    schedule:
      interval: "daily"
